[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
# ML library specific: PD, NPY
select = ["E", "F", "UP", "W", "I", "ISC", "C4", "SIM"]
ignore = [
    "E501", # line length
    "SIM112", # unsorted import block
]